version: '3'

services:

  web:
    build: .
    image: downtime_detector
    volumes:
      - .:/usr/src/downtime_detector
      - gems:/usr/local/bundle
    depends_on:
      - db
    ports:
      - '2300:2300'
    stdin_open: true
    tty: true
    command: bash -c 'bundle && bundle exec hanami server'

  sidekiq:
    image: downtime_detector
    volumes:
      - .:/usr/src/downtime_detector
      - gems:/usr/local/bundle
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    command: bash -c 'wait-for-it web:2300 --timeout=0 && bundle exec guard -n f -i -G .sidekiq.guardfile'

  db:
    image: postgres:13.3
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  redis:
    image: redis:6.2
    volumes:
      - redis:/data

volumes:
  gems:
  pg:
  redis:
