version: '3'

services:

  web:
    image: enjaku/downtime_detector:latest
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  sidekiq:
    image: enjaku/downtime_detector:latest
    depends_on:
      - db
      - redis
    command: bash -c "bundle exec sidekiq"

  db:
    image: postgres:12.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'

  redis:
    image: redis:6.0.1
    volumes:
      - ./tmp/redis:/data
