FROM ruby:2.6.6

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

ARG RAILS_MASTER_KEY

ENV RAILS_ENV=production
ENV RAILS_MASTER_KEY=$RAILS_MASTER_KEY
ENV DATABASE_HOST=db
ENV REDIS_URL=redis://redis:6379/0

RUN mkdir /downtime_detector
WORKDIR /downtime_detector

COPY Gemfile*

RUN bundle

COPY . /downtime_detector

RUN bin/rails assets:precompile
