FROM ruby:2.6.6

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client nano

ARG RAILS_MASTER_KEY

ENV RAILS_ENV=production
ENV RAILS_MASTER_KEY=$RAILS_MASTER_KEY
ENV REDIS_URL=redis://redis:6379/0

COPY Gemfile .
COPY Gemfile.lock .

RUN bundle install --without development test

COPY . .

RUN bundle exec rails assets:precompile

CMD bundle exec rails s -p $PORT -b '0.0.0.0'
