FROM ruby:2.6.6

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client curl

ARG RAILS_MASTER_KEY

ENV RAILS_ENV=production
ENV RAILS_MASTER_KEY=$RAILS_MASTER_KEY

COPY Gemfile .
COPY Gemfile.lock .

RUN bundle install --without development test

COPY . .

CMD bundle exec rails db:migrate
