:concurrency: 3
:max_retries: 0

:queues:
  - default
  - mailers

development:
  :schedule:
    ping_delegation_job:
      every: 1m
      class: PingingService::BulkPingWorker

production:
  :schedule:
    ping_delegation_job:
      every: 1m
      class: PingingService::BulkPingWorker