:concurrency: 3
:max_retries: 0

:queues:
  - default

development:
  :schedule:
    ping_delegation_job:
      every: 1m
      class: PingingService::BulkPingWorker
      enabled: false

production:
  :schedule:
    ping_delegation_job:
      every: 1m
      class: PingingService::BulkPingWorker