name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_HOST: localhost
      DISABLE_SPRING: 1

    services:
      db:
        image: postgres:12.2
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - run: sudo apt-get -yqq install libpq-dev
      - run: bundle config --local path vendor/bundle

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - run: bundle
      - run: bin/rails db:test:prepare
      - run: bin/rspec --format RSpec::Github::Formatter

  build:
    runs-on: ubuntu-latest

    needs: test

    # if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: enjaku
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          cache-from: type=registry,ref=enjaku/downtime_detector:latest
          cache-to: type=inline
          build-args: |
            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
          tags: |
            enjaku/downtime_detector:${{ github.sha }}
            enjaku/downtime_detector:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    # if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - run: echo ${{ secrets.SSH_PRIVATE_KEY }} > id_rsa.deploy
      - run: scp -i id_rsa.deploy docker-compose.prod.yml deploy.sh enjaku@161.35.92.31:/home/enjaku/apps/downtime_detector
      - run: ssh -i id_rsa.deploy enjaku@161.35.92.31 '/home/enjaku/apps/downtime_detector/deploy.sh'

      # - uses: appleboy/scp-action@master
      #   with:
      #     host: 161.35.92.31
      #     username: enjaku
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     source: ./docker-compose.prod.yml
      #     target: /home/enjaku/apps/downtime_detector

      # - uses: appleboy/ssh-action@master
      #   with:
      #     host: 161.35.92.31
      #     username: enjaku
      #     key: ${{ secrets.SSH_PRIVATE_KEY}}
      #     script: |
      #       docker pull enjaku/downtime_detector:latest
      #       docker-compose -f /home/enjaku/apps/downtime_detector/docker-compose.prod.yml run --rm web bin/rails db:migrate
      #       docker-compose -f /home/enjaku/apps/downtime_detector/docker-compose.prod.yml stop -t 30 sidekiq
      #       docker-compose -f /home/enjaku/apps/downtime_detector/docker-compose.prod.yml up -d web
      #       docker-compose -f /home/enjaku/apps/downtime_detector/docker-compose.prod.yml up -d sidekiq
      #       curl -X POST -H "Content-Type: application/json" -d '{"environment":"production","repository":"https://github.com/enjaku/downtime_detector","revision":"${{ github.sha }}"}' "https://airbrake.io/api/v4/projects/${{ secrets.AIRBRAKE_PROJECT_ID }}/deploys?key=${{ secrets.AIRBRAKE_PROJECT_KEY }}"
