name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BUNDLE_WITHOUT: development
      DATABASE_HOST: localhost
      HANAMI_ENV: test

    services:
      db:
        image: postgres:12.6
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.7
          bundler-cache: true

      - run: bundle exec hanami db create
      - run: bundle exec hanami db migrate
      - run: bundle exec rspec --format RSpec::Github::Formatter
