name: CI
# test gem cache
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_HOST: localhost

    services:
      db:
        image: postgres:12.2
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.6

      - run: bundle config --local path vendor/bundle

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - run: sudo apt-get -yqq install libpq-dev
      - run: bundle
      - run: |
          bin/rails db:test:prepare
          bin/rspec --format RSpec::Github::Formatter
